server:
  port: 18180

spring:
  application:
    name: dubbo-prometheus-demo

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: -1
  metrics:
    enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /
      path-mapping:
        metrics: actuator-metrics
        prometheus: metrics
  endpoint:
    health:
      show-details: always
